import type { CapacitorConfig } from "@capacitor/cli";

const config: CapacitorConfig = {
  appId: "com.bluvfi.xyz",
  appName: "Bluvfi",
  // The static export (generated by `yarn build:android`) lives in `out/`.
  // Capacitor copies it into android/app/src/main/assets/public so the
  // WebView can load it without any network connection.
  webDir: "out",

  // ── Server override (dev only) ────────────────────────────────────────────
  // CAPACITOR_DEV=1  → WebView loads the local Next.js dev server so you get
  //                    live reload without rebuilding the APK every time.
  // (unset)          → WebView loads the bundled static export from `out/`.
  ...(process.env.CAPACITOR_DEV === "1"
    ? {
        server: {
          url: "http://10.0.2.2:3000", // Android emulator → host localhost
          cleartext: true,
          androidScheme: "http",
        },
      }
    : {}),

  plugins: {
    App: {
      disableBackButtonHandler: false,
    },
  },
};

export default config;
